### ISSUE TITLE
Using ID's for unique selectors

### ISSUE THREAD

**Issue by zannain** [Eliphat/prj-rev-bwfs-dasmoto#2]
I like how you abstracted [CSS styles](https://github.com/Eliphat/prj-rev-bwfs-dasmoto/blob/master/Art/resources/css/artstyle.css#L16) such `background-color: lightcoral` to an attribute selector. This is in fact how popular CSS framework like Bootstrap work, they create a library of styles and you can apply them by calling the class. As an improvement, since these styles are unique to the element and only used once, rather than creating a class selector for them, an id selector would be more appropriate. 

```css
/* class selector not recommended */
.blue{background-color:skyblue;};}

/* Recommended */
#blue {
    background-color:skyblue;
}
```
