### ISSUE TITLE
Don't repeat your styles

### ISSUE THREAD

**Issue by zannain** [Eliphat/prj-rev-bwfs-dasmoto#3]
You may have come across the term [Dont-Repeat-Yourself](http://deviq.com/don-t-repeat-yourself/) before. It is generally considered a red flag when code begins to repeat and is an indication that there may be areas where code can be refactored. I noticed the styles [`font-family: Helvetica` and `font-weight: bold`](https://github.com/Eliphat/prj-rev-bwfs-dasmoto/blob/master/Art/resources/css/artstyle.css#L23-L24) used several times. If these are universal styles, using the `body` selector will apply these styles to the entire page. If they are specific for an element, then combining them would is a best practice because later if an updated is required then there will be no need to find everywhere that style was applied.

```css
/* Applying a style to the entire webpage */
body {
    font-family: Helvetica;
}

/* Styles specific to elements */
h1,
h2,
h3 {
    font-family: Helvetica;
    font-weight: bold;
}
```
